MODEL:
  NUM_CLASSES: 21
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("clipart_train",)
  TEST: ("clipart_test",)
SOLVER:
  MAX_ITER: 70000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: '/content/drive/MyDrive/ML_Project/SSD/outputs/vgg_ssd300_clipart_finetuned'

#SSD finetuned version 1, based on 500 clipart images